version: '3.7'

services:
  traefik:
    image: traefik:2.1
    #    restart: always
    ports:
      - "80:80"
    #      - "443:443"
    #      - "8080:8080"
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:delegated
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.rule=Host(`traefik.docker.localhost`)"
      - "traefik.http.routers.traefik.entrypoints=http"
