version: "3.7"

services:
  web:
    image: ${DOCKER_SERVICE_WEB_IMAGE}
    volumes:
      - .:/project:delegated
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini:delegated
      - ./conf/httpd/extra/httpd-vhosts.conf:/etc/apache2/sites-enabled/httpd-vhosts.conf:delegated
      # Composer cache.
      - ~/.cache/composer/:/root/.composer/cache/
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}_web.entrypoints=http"
      - "traefik.http.routers.${PROJECT_NAME}_web.rule=Host(`${DRUPAL_SITE_DEFAULT_DOMAIN_1}`, `${DRUPAL_SITE_DEFAULT_DOMAIN_2}`, `${DRUPAL_SITE_DEFAULT_DOMAIN_3}`)"
      - "traefik.http.routers.${PROJECT_NAME}_web.middlewares=redirect-to-https@file"
      - "traefik.http.routers.${PROJECT_NAME}_web_secure.entrypoints=https"
      - "traefik.http.routers.${PROJECT_NAME}_web_secure.rule=Host(`${DRUPAL_SITE_DEFAULT_DOMAIN_1}`, `${DRUPAL_SITE_DEFAULT_DOMAIN_2}`, `${DRUPAL_SITE_DEFAULT_DOMAIN_3}`)"
      - "traefik.http.routers.${PROJECT_NAME}_web_secure.tls=true"
    networks:
      default:
        # Aliases for Docker network to have the containers aware of this domain
        # names.
        aliases:
          - ${DRUPAL_SITE_DEFAULT_DOMAIN_1}
          - ${DRUPAL_SITE_DEFAULT_DOMAIN_2}
          - ${DRUPAL_SITE_DEFAULT_DOMAIN_3}
    depends_on:
      - mysql
      - redis
      - mail


  varnish:
    image: ${DOCKER_SERVICE_VARNISH_IMAGE}
    volumes:
      - ./conf/varnish:/varnish-drupal:delegated
    environment:
      VCL_CONFIG: /varnish-drupal/varnish.vcl
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}_varnish.entrypoints=http"
      - "traefik.http.routers.${PROJECT_NAME}_varnish.rule=Host(`${VARNISH_DOMAIN}`)"
      - "traefik.http.routers.${PROJECT_NAME}_varnish.middlewares=redirect-to-https@file"
      - "traefik.http.routers.${PROJECT_NAME}_varnish_secure.entrypoints=https"
      - "traefik.http.routers.${PROJECT_NAME}_varnish_secure.rule=Host(`${VARNISH_DOMAIN}`)"
      - "traefik.http.routers.${PROJECT_NAME}_varnish_secure.tls=true"
    depends_on:
      - web


  mysql:
    image: ${DOCKER_SERVICE_DRUPAL_SITE_DEFAULT_DB_IMAGE}
    environment:
      MYSQL_ROOT_PASSWORD: ${DRUPAL_SITE_DEFAULT_DB_ROOT_PASSWORD}
      MYSQL_USER: ${DRUPAL_SITE_DEFAULT_DB_USER}
      MYSQL_PASSWORD: ${DRUPAL_SITE_DEFAULT_DB_PASSWORD}
      MYSQL_DATABASE: ${DRUPAL_SITE_DEFAULT_DB_DATABASE}
    volumes:
      - ./conf/mysql:/etc/mysql/conf.d:delegated
      - ./data/db:/var/lib/mysql:delegated


  solr:
    image: ${DOCKER_SERVICE_SOLR_IMAGE}
    volumes:
      - ./conf/solr:/solr-drupal/conf:delegated
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - drupal
      - /solr-drupal


  redis:
    image: ${DOCKER_SERVICE_REDIS_IMAGE}
    volumes:
      - ./conf/redis/redis.conf:/usr/local/etc/redis/redis.conf:delegated
    entrypoint:
      - docker-entrypoint.sh
      - /usr/local/etc/redis/redis.conf


  mail:
    image: djfarrelly/maildev
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.${PROJECT_NAME}_mail.loadbalancer.server.port=80"
      - "traefik.http.routers.${PROJECT_NAME}_mail.entrypoints=http"
      - "traefik.http.routers.${PROJECT_NAME}_mail.rule=Host(`${MAIL_DOMAIN}`)"
      - "traefik.http.routers.${PROJECT_NAME}_mail.middlewares=redirect-to-https@file"
      - "traefik.http.routers.${PROJECT_NAME}_mail_secure.entrypoints=https"
      - "traefik.http.routers.${PROJECT_NAME}_mail_secure.rule=Host(`${MAIL_DOMAIN}`)"
      - "traefik.http.routers.${PROJECT_NAME}_mail_secure.tls=true"

  ## For development.
  # For tests.
  chrome:
    image: drupalci/webdriver-chromedriver:production
    ulimits:
      core:
        soft: -1
        hard: -1
#    ports:
#      - "4444:4444"
#      - "9515:9515"
    entrypoint:
      - chromedriver
      - "--log-path=/tmp/chromedriver.log"
      - "--verbose"
      - "--whitelisted-ips="

  node:
    image: ${DOCKER_SERVICE_NODE_IMAGE}
    volumes:
      - .:/project:delegated
    tty: true

  # Matomo.
  matomo:
    image: ${DOCKER_SERVICE_MATOMO_IMAGE}
    volumes:
     - type: volume
       source: matomo-volume
       target: /var/www/html
       consistency: delegated

  matomo_web:
    image: ${DOCKER_SERVICE_MATOMO_WEB_IMAGE}
    volumes:
      - type: bind
        source: ./conf/matomo_nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
        consistency: delegated
      - type: volume
        source: matomo-volume
        target: /var/www/html
        consistency: delegated
    environment:
      - VIRTUAL_HOST
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}_matomo_web.entrypoints=http"
      - "traefik.http.routers.${PROJECT_NAME}_matomo_web.rule=Host(`${MATOMO_DOMAIN}`)"
      - "traefik.http.routers.${PROJECT_NAME}_matomo_web.middlewares=redirect-to-https@file"
      - "traefik.http.routers.${PROJECT_NAME}_matomo_web_secure.entrypoints=https"
      - "traefik.http.routers.${PROJECT_NAME}_matomo_web_secure.rule=Host(`${MATOMO_DOMAIN}`)"
      - "traefik.http.routers.${PROJECT_NAME}_matomo_web_secure.tls=true"
    networks:
      default:
        aliases:
          - ${MATOMO_DOMAIN}

  matomo_mysql:
    image: ${DOCKER_SERVICE_MATOMO_DB_IMAGE}
    environment:
      MYSQL_ROOT_PASSWORD: ${MATOMO_DB_ROOT_PASSWORD}
      MYSQL_USER: ${MATOMO_DB_USER}
      MYSQL_PASSWORD: ${MATOMO_DB_PASSWORD}
      MYSQL_DATABASE: ${MATOMO_DB_DATABASE}
    volumes:
      - ./conf/mysql:/etc/mysql/conf.d:delegated
      - ./data/matomo_db:/var/lib/mysql:delegated

volumes:
  matomo-volume:
