version: "3.7"

services:
  web:
    image: florenttorregrosa/drupal-php-dev:7.3-apache
    volumes:
      - .:/project:delegated
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini:delegated
      - ./conf/httpd/extra/httpd-vhosts.conf:/etc/apache2/sites-enabled/httpd-vhosts.conf:delegated
    environment:
      - DRUPAL_TRAEFIK_FRONTEND_RULE_HOSTNAME=${DRUPAL_TRAEFIK_FRONTEND_RULE_HOSTNAME:-web.ddp8.docker.localhost}
      - VARNISH_TRAEFIK_FRONTEND_RULE_HOSTNAME=${VARNISH_TRAEFIK_FRONTEND_RULE_HOSTNAME:-varnish.ddp8.docker.localhost}
      - COMPOSER_ALLOW_SUPERUSER=1
      - XDEBUG_HOST=${XDEBUG_HOST:-172.17.0.1}
      - XDEBUG_ENABLED=${XDEBUG_ENABLED:-false}
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${DRUPAL_TRAEFIK_FRONTEND_RULE_HOSTNAME:-web.ddp8.docker.localhost}"
    networks:
      default:
        aliases:
          - ${DRUPAL_FRONTEND_ALIAS_0:-web.ddp8.docker.localhost}
          - ${DRUPAL_FRONTEND_ALIAS_1:-en-web.ddp8.docker.localhost}
          - ${DRUPAL_FRONTEND_ALIAS_2:-fr-web.ddp8.docker.localhost}
    depends_on:
      - mysql
      - redis
      - mail


  varnish:
    image: florenttorregrosa/varnish:6-alpine
    volumes:
      - ./conf/varnish:/varnish-drupal:delegated
    environment:
      VCL_CONFIG: /varnish-drupal/varnish.vcl
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${VARNISH_TRAEFIK_FRONTEND_RULE_HOSTNAME:-varnish.ddp8.docker.localhost}"
    depends_on:
      - web


  mysql:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal
    volumes:
      - ./conf/mysql:/etc/mysql/conf.d:delegated
      - ./data/db:/var/lib/mysql:delegated


  solr:
    image: solr:7.6-alpine
    volumes:
      - ./conf/solr:/solr-drupal/conf:delegated
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - drupal
      - /solr-drupal


  redis:
    image: redis:5.0-alpine
    volumes:
      - ./conf/redis/redis.conf:/usr/local/etc/redis/redis.conf:delegated
    entrypoint:
      - docker-entrypoint.sh
      - /usr/local/etc/redis/redis.conf


  mail:
    image: djfarrelly/maildev
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${MAIL_TRAEFIK_FRONTEND_RULE_HOSTNAME:-mail.ddp8.docker.localhost}"
      - "traefik.port=80"

  # For tests.
  chrome:
    image: drupalci/webdriver-chromedriver:production
    ulimits:
      core:
        soft: -1
        hard: -1
    ports:
      - "4444:4444"
      - "9515:9515"
    entrypoint:
      - chromedriver
      - "--log-path=/tmp/chromedriver.log"
      - "--verbose"
      - "--whitelisted-ips="

  # Matomo.
  matomo:
    image: matomo:3.9-fpm
    volumes:
     - type: volume
       source: matomo-volume
       target: /var/www/html
       consistency: delegated

  matomo_web:
    image: nginx:1.15-alpine
    volumes:
      - type: bind
        source: ./conf/matomo_nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
        consistency: delegated
      - type: volume
        source: matomo-volume
        target: /var/www/html
        consistency: delegated
    environment:
      - VIRTUAL_HOST
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${MATOMO_TRAEFIK_FRONTEND_RULE_HOSTNAME:-matomo.ddp8.docker.localhost}"
    networks:
      default:
        aliases:
          - ${MATOMO_TRAEFIK_FRONTEND_RULE_HOSTNAME:-matomo.ddp8.docker.localhost}

  matomo_mysql:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: matomo
      MYSQL_PASSWORD: matomo
      MYSQL_DATABASE: matomo
    volumes:
      - ./conf/mysql:/etc/mysql/conf.d:delegated
      - ./data/matomo_db:/var/lib/mysql:delegated

volumes:
  matomo-volume:
