version: "2"

services:
  web:
    extends:
      file: ./docker-compose-common.yml
      service: drupal-php-apache-dev
    networks:
      - traefik_webgateway
      - default
    depends_on:
      - mysql
      - redis
      - mail

  varnish:
    extends:
      file: ./docker-compose-common.yml
      service: varnish
    networks:
      - traefik_webgateway
      - default
    depends_on:
      - web

  mysql:
    extends:
      file: ./docker-compose-common.yml
      service: mysql
    environment:
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal
    volumes:
      - ./data/db:/var/lib/mysql


  solr:
    extends:
      file: ./docker-compose-common.yml
      service: solr


  redis:
    extends:
      file: ./docker-compose-common.yml
      service: redis


  mail:
    extends:
      file: ./docker-compose-common.yml
      service: mail
    networks:
      - traefik_webgateway
      - default

  # Piwik.
  piwik:
    image: piwik:3.2-fpm

  piwik_web:
    extends:
      file: ./docker-compose-common.yml
      service: piwik_nginx
    volumes_from:
      - piwik
    networks:
      - traefik_webgateway
      - default

  piwik_mysql:
    extends:
      file: ./docker-compose-common.yml
      service: mysql
    environment:
      MYSQL_USER: piwik
      MYSQL_PASSWORD: piwik
      MYSQL_DATABASE: piwik
    volumes:
      - ./data/piwik_db:/var/lib/mysql

networks:
  traefik_webgateway:
    external: true
