version: "2"

services:
  web:
#    image: httpd:2.4-alpine
#    volumes:
#      - ./conf/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
#      - ./conf/httpd/extra/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
#      - .:/project

#    image: nginx:1.11-alpine
#    volumes:
#      - ./conf/nginx:/etc/nginx/conf.d/
#      - .:/project

#    image: florenttorregrosa/docker-drupal:php7
#    build:
#      context: ./docker-images/php-apache
    image: florenttorregrosa/docker-drupal-dev:php7
#    build:
#      context: ./docker-images/php-apache-dev
    volumes:
      - .:/project
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini
      - ./conf/httpd/extra/httpd-vhosts.conf:/etc/apache2/sites-enabled/httpd-vhosts.conf
    depends_on:
      - php
      - mysql
      - redis
      - mail
      - solr
    networks:
      default:
        ipv4_address: 172.21.0.2


#  php:
#    image: florenttorregrosa/drupal-php:7.0-fpm-alpine
#    build:
#      context: ./docker-images/php
#    image: florenttorregrosa/drupal-php-dev:7.0-fpm-alpine
#    build:
#      context: ./docker-images/php-dev
#    volumes:
#      - .:/project
#      - ./conf/php/php.ini:/usr/local/etc/php/php.ini
#    networks:
#      default:
#        ipv4_address: 172.21.0.3


  varnish:
    image: florenttorregrosa/docker-varnish:latest
#    build:
#      context: ./docker-images/varnish
    depends_on:
      - web
    environment:
      VCL_CONFIG: /varnish-drupal/varnish.vcl
    volumes:
      - ./conf/varnish:/varnish-drupal
    networks:
      default:
        ipv4_address: 172.21.0.4


  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal
    volumes:
      - ./data/db:/var/lib/mysql
      - ./conf/mysql:/etc/mysql/conf.d
    networks:
      default:
        ipv4_address: 172.21.0.5


  solr:
    image: solr:6.2-alpine
    volumes:
      - ./conf/solr:/solr-drupal/conf
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - drupal
      - /solr-drupal
    networks:
      default:
        ipv4_address: 172.21.0.6


  elasticsearch:
    image: elasticsearch:2.4
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
      - ./conf/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      default:
        ipv4_address: 172.21.0.7


  redis:
    image: redis:3.2-alpine
    networks:
      default:
        ipv4_address: 172.21.0.8


  mail:
    image: djfarrelly/maildev
    networks:
      default:
        ipv4_address: 172.21.0.9


  # Piwik.
  piwik:
    image: piwik:2.17
    links:
      - piwik_mysql
    networks:
      default:
        ipv4_address: 172.21.0.15

  piwik_web:
    image: nginx:1.11-alpine
    volumes:
      - ./conf/piwik_nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - piwik
    volumes_from:
      - piwik
    environment:
      - VIRTUAL_HOST
    networks:
      default:
        ipv4_address: 172.21.0.17

  piwik_mysql:
    image: mysql:5.7
    volumes:
      - ./data/piwik_db:/var/lib/mysql
      - ./conf/mysql:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: piwik
      MYSQL_PASSWORD: piwik
      MYSQL_DATABASE: piwik
    networks:
      default:
        ipv4_address: 172.21.0.16

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.21.0.0/16
        gateway: 172.21.0.1
