version: "2"

services:
  web:
    extends:
      file: ./docker-compose-common.yml
      service: drupal-php-apache-dev
    ports:
      - 8081:80
    depends_on:
      - mysql
      - redis
      - mail


#  php:
#    extends:
#      file: ./docker-compose-common.yml
#      service: drupal-php-dev


  varnish:
    extends:
      file: ./docker-compose-common.yml
      service: varnish
    depends_on:
      - web
    ports:
      - 8080:80


  mysql:
    extends:
      file: ./docker-compose-common.yml
      service: mysql
    environment:
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal
    volumes:
      - ./data/db:/var/lib/mysql


  solr:
    extends:
      file: ./docker-compose-common.yml
      service: solr


  elasticsearch:
    extends:
      file: ./docker-compose-common.yml
      service: elasticsearch


  redis:
    image: redis:3.2-alpine


  mail:
    image: djfarrelly/maildev
    ports:
      - 8085:80


  # Piwik.
  piwik:
    image: piwik:3.0

  piwik_web:
    extends:
      file: ./docker-compose-common.yml
      service: piwik_nginx
    volumes_from:
      - piwik
    ports:
      - 8082:80

  piwik_mysql:
    extends:
      file: ./docker-compose-common.yml
      service: mysql
    environment:
      MYSQL_USER: piwik
      MYSQL_PASSWORD: piwik
      MYSQL_DATABASE: piwik
    volumes:
      - ./data/piwik_db:/var/lib/mysql
