version: "2.3"

services:
  web:
    extends:
      file: ./docker-compose-common.yml
      service: drupal-php-apache-dev
    environment:
      - DRUPAL_TRAEFIK_FRONTEND_RULE_HOSTNAME=${DRUPAL_TRAEFIK_FRONTEND_RULE_HOSTNAME:-web.ddp8.docker.localhost}
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${DRUPAL_TRAEFIK_FRONTEND_RULE_HOSTNAME:-web.ddp8.docker.localhost}"
    depends_on:
      - mysql
      - redis
      - mail

  php_cli:
    extends:
      file: ./docker-compose-common.yml
      service: php-cli-dev
    depends_on:
      - mysql
      - redis
      - mail

  varnish:
    extends:
      file: ./docker-compose-common.yml
      service: varnish
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${VARNISH_TRAEFIK_FRONTEND_RULE_HOSTNAME:-varnish.ddp8.docker.localhost}"
    depends_on:
      - web

  mysql:
    extends:
      file: ./docker-compose-common.yml
      service: mysql
    environment:
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal
    volumes:
      - ./data/db:/var/lib/mysql


  solr:
    extends:
      file: ./docker-compose-common.yml
      service: solr


  redis:
    extends:
      file: ./docker-compose-common.yml
      service: redis


  mail:
    extends:
      file: ./docker-compose-common.yml
      service: mail
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${MAIL_TRAEFIK_FRONTEND_RULE_HOSTNAME:-mail.ddp8.docker.localhost}"
      - "traefik.port=80"

  # Piwik.
  piwik:
    image: piwik:3.2-fpm

  piwik_web:
    extends:
      file: ./docker-compose-common.yml
      service: piwik_nginx
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${PIWIK_TRAEFIK_FRONTEND_RULE_HOSTNAME:-piwik.ddp8.docker.localhost}"
    volumes_from:
      - piwik

  piwik_mysql:
    extends:
      file: ./docker-compose-common.yml
      service: mysql
    environment:
      MYSQL_USER: piwik
      MYSQL_PASSWORD: piwik
      MYSQL_DATABASE: piwik
    volumes:
      - ./data/piwik_db:/var/lib/mysql
