version: "2"

services:
  web:
#    image: florenttorregrosa/httpd:2.4
    image: httpd:2.4-alpine
#    build:
#      context: ./docker-images/httpd/
#    depends_on:
#      - mysql
#      - redis
#      - mail
#      - solr
#      - php
    volumes:
      - ./conf/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./conf/httpd/extra/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
#      - .:/usr/local/apache2/htdocs/
#      - ./www:/var/www/html
      - .:/project
    networks:
      default:
        ipv4_address: 172.21.0.2

  nginx:
    image: nginx:1.11-alpine
#    depends_on:
#      - mysql
#      - redis
#      - mail
#      - solr
#      - php
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d/
#      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./www:/var/www/html
      - .:/project
    networks:
      default:
        ipv4_address: 172.21.0.10


  php:
    image: florenttorregrosa/php:7.0-fpm
    build:
      context: ./docker-images/php/
    volumes:
#      - ./www:/var/www/html
      - .:/project
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini
    expose:
      - 9000
    networks:
      default:
        ipv4_address: 172.21.0.3

#  llaumgui_centos7-scl-httpd24:
#    container_name: llaumgui_centos7-scl-httpd24
#    image: llaumgui/centos7-scl-httpd24
#    restart: always
#    mem_limit: 512m
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - ./www:/var/www/html
#      - ./volumes/conf/httpd24/vhost.d:/etc/httpd/vhost.d:ro
#      - ./volumes/log/httpd24:/var/log/httpd24
#    networks:
#      default:
#        ipv4_address: 172.21.0.2
#    ports:
#      - 88:80
#    links:
#     - llaumgui_centos7-scl-php56:php56


#  llaumgui_centos7-scl-php56:
#    container_name: llaumgui_centos7-scl-php56
#    image: llaumgui/centos7-scl-php56
#    build:
#      context: ../docker-images/php-fpm/5.6/
#    restart: always
#    mem_limit: 1g
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - ./www:/var/www/html
#      - ./volumes/conf/php56/90-custom.ini:/etc/php.d/90-custom.ini:ro
#      - ./volumes/log/php56:/var/log/php-fpm
#    networks:
#      default:
#        ipv4_address: 172.21.0.3
#    expose:
#      - 9000
#    links:
#     - mariadb10:container_database
#     - memcached:container_memcached
#     - llaumgui_centos7-sphinxse:container_sphinx


#  varnish:
#    image: florenttorregrosa/docker-varnish:latest
#    depends_on:
#      - web
#    environment:
#      VCL_CONFIG: /varnish-drupal/varnish.vcl
#    volumes:
#      - ./conf/varnish:/varnish-drupal
#    networks:
#      default:
#        ipv4_address: 172.21.0.4
#
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal
    volumes:
      - ./data/db:/var/lib/mysql
      - ./conf/mysql:/etc/mysql/conf.d
    networks:
      default:
        ipv4_address: 172.21.0.5
#
#
#  solr:
#    image: solr:6.1.0-alpine
#    volumes:
#      - ./conf/solr:/solr-drupal/conf
#    entrypoint:
#      - docker-entrypoint.sh
#      - solr-precreate
#      - drupal
#      - /solr-drupal
#    networks:
#      default:
#        ipv4_address: 172.21.0.6
#
#
#  redis:
#    image: redis:3.2.1-alpine
#    networks:
#      default:
#        ipv4_address: 172.21.0.7
#
#
  mail:
    image: djfarrelly/maildev
    networks:
      default:
        ipv4_address: 172.21.0.8


networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.21.0.0/16
        gateway: 172.21.0.1
