version: "2.3"

services:
  web:
    extends:
      file: ./docker-compose-common.yml
      service: drupal-php-apache-dev
    environment:
      - DRUPAL_TRAEFIK_FRONTEND_RULE_HOSTNAME=${DRUPAL_TRAEFIK_FRONTEND_RULE_HOSTNAME:-web.ddp8.docker.localhost}
      - VARNISH_TRAEFIK_FRONTEND_RULE_HOSTNAME=${VARNISH_TRAEFIK_FRONTEND_RULE_HOSTNAME:-varnish.ddp8.docker.localhost}
      - COMPOSER_ALLOW_SUPERUSER=1
      - XDEBUG_HOST=${XDEBUG_HOST:-172.17.0.1}
      - XDEBUG_ENABLED=${XDEBUG_ENABLED:-false}
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${DRUPAL_TRAEFIK_FRONTEND_RULE_HOSTNAME:-web.ddp8.docker.localhost}"
    depends_on:
      - mysql
      - redis
      - mail

  varnish:
    extends:
      file: ./docker-compose-common.yml
      service: varnish
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${VARNISH_TRAEFIK_FRONTEND_RULE_HOSTNAME:-varnish.ddp8.docker.localhost}"
    depends_on:
      - web

  mysql:
    extends:
      file: ./docker-compose-common.yml
      service: mysql
    environment:
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal
    volumes:
      - ./data/db:/var/lib/mysql


  solr:
    extends:
      file: ./docker-compose-common.yml
      service: solr


  redis:
    extends:
      file: ./docker-compose-common.yml
      service: redis


  mail:
    extends:
      file: ./docker-compose-common.yml
      service: mail
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${MAIL_TRAEFIK_FRONTEND_RULE_HOSTNAME:-mail.ddp8.docker.localhost}"
      - "traefik.port=80"

  # Matomo.
  matomo:
    image: matomo:3.8-fpm

  matomo_web:
    extends:
      file: ./docker-compose-common.yml
      service: matomo_nginx
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${MATOMO_TRAEFIK_FRONTEND_RULE_HOSTNAME:-matomo.ddp8.docker.localhost}"
    volumes_from:
      - matomo

  matomo_mysql:
    extends:
      file: ./docker-compose-common.yml
      service: mysql
    environment:
      MYSQL_USER: matomo
      MYSQL_PASSWORD: matomo
      MYSQL_DATABASE: matomo
    volumes:
      - ./data/matomo_db:/var/lib/mysql
